import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/_main.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "login page",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <div className={inter.className}>{children}</div>

    );
}
