import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/_main.css'
import { mr } from '@/lib/mr'
import { Stepper } from '@/components/steps/stepper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Organisation configuration page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className={mr(inter.className, 'w-full h-screen flex')}>
      <div className='w-[375px] bg-gray-100 flex items-center justify-center'>
        <Stepper />
      </div>
      <div className='bg-white flex-1 flex items-center justify-center flex-col'>
        <div className='flex-1 flex items-center justify-center w-full'>{children}</div>
      </div>
    </div>
  )
}
