export enum BUSINESS_TYPE {
  CORPORATION = 'CORPORATION',
  PARTNERSHIP = 'PARTNERSHIP',
  NON_PROFIT = 'NON_PROFIT',
  COOPERATIVE = 'COOPERATIVE',
  STARTUP = 'STARTUP',
  SOLE_PROPRIETORSHIP = 'SOLE_PROPRIETORSHIP',
  OTHERS = 'OTHERS',
}
