import '@/styles/_main.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { mr } from '@/lib/mr'
import { Stepper } from '@/components/steps/stepper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Organisation configuration page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className={mr(inter.className, 'flex overflow-hidden h-screen')}>
      <div className='w-[500px] h-screen bg-gray-100 flex items-center justify-center'>
        <Stepper />
      </div>

      <div className='flex-1 bg-white overflow-auto'>
        <div className='p-4'>{children}</div>
      </div>
    </div>
  )
}
