export enum ESTIMATE_STATUS {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  SENT = 'SENT',
  VIEWED = 'VIEWED',
  EXPIRED = 'EXPIRED',
  CONVERTED = 'CONVERTED',
}
