export const CURRENCIES: { label: string; value: string }[] = [
  { label: 'Tunisian Dinar', value: 'TND' },
  { label: 'US Dollar', value: 'USD' },
  { label: 'Euro', value: 'EUR' },
  { label: 'British Pound', value: 'GBP' },
  { label: 'Japanese Yen', value: 'JPY' },
  { label: 'Swiss Franc', value: 'CHF' },
  { label: 'Australian Dollar', value: 'AUD' },
  { label: 'Canadian Dollar', value: 'CAD' },
  { label: 'Chinese Yuan', value: 'CNY' },
  { label: 'Indian Rupee', value: 'INR' },
  { label: 'Brazilian Real', value: 'BRL' },
  { label: 'Mexican Peso', value: 'MXN' },
  { label: 'Singapore Dollar', value: 'SGD' },
  { label: 'Hong Kong Dollar', value: 'HKD' },
  { label: 'South Korean Won', value: 'KRW' },
  { label: 'Russian Ruble', value: 'RUB' },
  { label: 'South African Rand', value: 'ZAR' },
  { label: 'New Zealand Dollar', value: 'NZD' },
  { label: 'Turkish Lira', value: 'TRY' },
  { label: 'Swedish Krona', value: 'SEK' },
  { label: 'Norwegian Krone', value: 'NOK' },
  { label: 'Danish Krone', value: 'DKK' },
  { label: 'Polish Zloty', value: 'PLN' },
  { label: 'Hungarian Forint', value: 'HUF' },
  { label: 'Czech Koruna', value: 'CZK' },
  { label: 'Israeli Shekel', value: 'ILS' },
  { label: 'Saudi Riyal', value: 'SAR' },
  { label: 'Emirati Dirham', value: 'AED' },
  { label: 'Egyptian Pound', value: 'EGP' },
  { label: 'Thai Baht', value: 'THB' },
  { label: 'Malaysian Ringgit', value: 'MYR' },
  { label: 'Indonesian Rupiah', value: 'IDR' },
  { label: 'Philippine Peso', value: 'PHP' },
  { label: 'Taiwan Dollar', value: 'TWD' },
  { label: 'Argentine Peso', value: 'ARS' },
  { label: 'Chilean Peso', value: 'CLP' },
  { label: 'Colombian Peso', value: 'COP' },
  { label: 'Peruvian Sol', value: 'PEN' },
  { label: 'Venezuelan Bolívar', value: 'VES' },
  { label: 'Bolivian Boliviano', value: 'BOB' },
  { label: 'Costa Rican Colón', value: 'CRC' },
  { label: 'Dominican Peso', value: 'DOP' },
  { label: 'Guatemalan Quetzal', value: 'GTQ' },
  { label: 'Honduran Lempira', value: 'HNL' },
  { label: 'Nicaraguan Córdoba', value: 'NIO' },
  { label: 'Panamanian Balboa', value: 'PAB' },
  { label: 'Paraguayan Guaraní', value: 'PYG' },
  { label: 'Uruguayan Peso', value: 'UYU' },
  { label: 'Cuban Convertible Peso', value: 'CUC' },
  { label: 'Cuban Peso', value: 'CUP' },
  { label: 'Fijian Dollar', value: 'FJD' },
  { label: 'Jamaican Dollar', value: 'JMD' },
  { label: 'Bahamian Dollar', value: 'BSD' },
  { label: 'Barbadian Dollar', value: 'BBD' },
  { label: 'Belize Dollar', value: 'BZD' },
  { label: 'East Caribbean Dollar', value: 'XCD' },
  { label: 'Guyanese Dollar', value: 'GYD' },
  { label: 'Surinamese Dollar', value: 'SRD' },
  { label: 'Trinidad and Tobago Dollar', value: 'TTD' },
  { label: 'Comorian Franc', value: 'KMF' },
  { label: 'Djiboutian Franc', value: 'DJF' },
  { label: 'Eritrean Nakfa', value: 'ERN' },
  { label: 'Ethiopian Birr', value: 'ETB' },
  { label: 'Seychellois Rupee', value: 'SCR' },
  { label: 'Somali Shilling', value: 'SOS' },
  { label: 'Swazi Lilangeni', value: 'SZL' },
  { label: 'Tanzanian Shilling', value: 'TZS' },
  { label: 'Ugandan Shilling', value: 'UGX' },
  { label: 'Angolan Kwanza', value: 'AOA' },
  { label: 'Botswana Pula', value: 'BWP' },
  { label: 'Burundian Franc', value: 'BIF' },
  { label: 'Cape Verdean Escudo', value: 'CVE' },
  { label: 'Central African CFA Franc', value: 'XAF' },
  { label: 'CFA Franc BCEAO', value: 'XOF' },
  { label: 'CFA Franc BEAC', value: 'XAF' },
  { label: 'Comorian Franc', value: 'KMF' },
  { label: 'Congolese Franc', value: 'CDF' },
  { label: 'Djiboutian Franc', value: 'DJF' },
  { label: 'Equatorial Guinean Ekwele', value: 'GQE' },
  { label: 'Eritrean Nakfa', value: 'ERN' },
  { label: 'Ethiopian Birr', value: 'ETB' },
  { label: 'Gabonese Franc', value: 'XAF' },
  { label: 'Gambian Dalasi', value: 'GMD' },
  { label: 'Guinean Franc', value: 'GNF' },
  { label: 'Kenyan Shilling', value: 'KES' },
  { label: 'Lesotho Loti', value: 'LSL' },
  { label: 'Liberian Dollar', value: 'LRD' },
  { label: 'Libyan Dinar', value: 'LYD' },
  { label: 'Malagasy Ariary', value: 'MGA' },
  { label: 'Malawian Kwacha', value: 'MWK' },
  { label: 'Mauritanian Ouguiya', value: 'MRU' },
  { label: 'Mauritian Rupee', value: 'MUR' },
  { label: 'Moldovan Leu', value: 'MDL' },
  { label: 'Moroccan Dirham', value: 'MAD' },
  { label: 'Mozambican Metical', value: 'MZN' },
  { label: 'Namibian Dollar', value: 'NAD' },
  { label: 'Nigerian Naira', value: 'NGN' },
  { label: 'Rwandan Franc', value: 'RWF' },
  { label: 'Saint Helena Pound', value: 'SHP' },
  { label: 'São Tomé and Príncipe Dobra', value: 'STN' },
  { label: 'Sierra Leonean Leone', value: 'SLL' },
  { label: 'Solomon Islands Dollar', value: 'SBD' },
  { label: 'South Sudanese Pound', value: 'SSP' },
  { label: 'Sudanese Pound', value: 'SDG' },
  { label: 'Swazi Lilangeni', value: 'SZL' },
  { label: 'Tanzanian Shilling', value: 'TZS' },
  { label: 'Togolese Franc', value: 'XOF' },
  { label: 'Ugandan Shilling', value: 'UGX' },
  { label: 'Zambian Kwacha', value: 'ZMW' },
  { label: 'Zimbabwean Dollar', value: 'ZWL' },
]
