export const INDUSTRIES_BUSINESS: { label: string; value: string }[] = [
  { label: 'IT Consulting', value: 'it consulting' },
  { label: 'Finance', value: 'finance' },
  { label: 'Healthcare', value: 'healthcare' },
  { label: 'Manufacturing', value: 'manufacturing' },
  { label: 'Retail', value: 'retail' },
  { label: 'Real Estate', value: 'real estate' },
  { label: 'Hospitality', value: 'hospitality' },
  { label: 'Education', value: 'education' },
  { label: 'Transportation', value: 'transportation' },
  { label: 'Construction', value: 'construction' },
  { label: 'Telecommunications', value: 'telecommunications' },
  { label: 'Media', value: 'media' },
  { label: 'Energy', value: 'energy' },
  { label: 'Automotive', value: 'automotive' },
  { label: 'Agriculture', value: 'agriculture' },
  { label: 'Legal', value: 'legal' },
  { label: 'Insurance', value: 'insurance' },
  { label: 'Entertainment', value: 'entertainment' },
  { label: 'Advertising', value: 'advertising' },
  { label: 'Technology', value: 'technology' },
  { label: 'Consulting', value: 'consulting' },
  { label: 'Architecture', value: 'architecture' },
  { label: 'Biotechnology', value: 'biotechnology' },
  { label: 'E-commerce', value: 'e-commerce' },
  { label: 'Food and Beverage', value: 'food and beverage' },
  { label: 'Gaming', value: 'gaming' },
  { label: 'Human Resources', value: 'human resources' },
  { label: 'Marketing', value: 'marketing' },
  { label: 'Pharmaceuticals', value: 'pharmaceuticals' },
  { label: 'Public Relations', value: 'public relations' },
  { label: 'Security', value: 'security' },
  { label: 'Software Development', value: 'software development' },
  { label: 'Travel and Tourism', value: 'travel and tourism' },
  { label: 'Waste Management', value: 'waste management' },
]
